project:
  type: website

website:
  title: "Aaron Zalen"
  navbar:
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false