project:
  type: website
  output-dir: .   
  
website:
  title: "Aaron Zalen"
  navbar:
    left:
      - text: Blog
        href: blog-listing.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false